spring:
  application:
    name: ai-generated-tweet-to-kafka-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      username: spring_cloud_user
      password: springCloud_Pwd!