akhq:
  connections:
    kafka-local:
      properties:
        bootstrap.servers: "kafka-broker-1:9092,kafka-broker-2:9092,kafka-broker-3:9092"
      schema-registry:
        url: http://apicurio-registry:8080/apis/registry/v2
