global:
  scrape_interval: 10s

scrape_configs:
  - job_name: kafka
    static_configs:
      - targets:
          - kafka-broker-1:9999
          - kafka-broker-2:9999
          - kafka-broker-3:9999
